version: '3'
services:
        web:
                image: dumbtrade_port
                build: .
                ports:
                        - "8060:8080"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
